url: 'https://quasician.github.io/porfolioSite/' # your main domain
baseurl: '/porfolioSite/' # if you're using custom domain keep this blank example: baseurl: ''


theme: jekyll-theme-minimal
markdown: GFM
